# -*- coding: utf-8 -*-
"""DEMO recommendation system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qNLASDHGr5QszJQKO0o261BHPIM6AuQN
"""

!pip install anthropic spacy
!python -m spacy download en_core_web_sm

import os
os.environ["ANTHROPIC_API_KEY"] = "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"

import anthropic

# ─────────────────────────────────────────────
# QUESTION BANK — Year 8 Math (20 questions)
# Each wrong option is tagged with the exact
# misconception it reveals about the student
# ─────────────────────────────────────────────

question_bank = [

    # ── ALGEBRA ──────────────────────────────
    {
        "id": 1,
        "topic": "Algebra",
        "subtopic": "Solving linear equations",
        "question": "Solve for x: 3x + 5 = 20",
        "correct": "A",
        "options": {
            "A": {"answer": "x = 5",    "misconception": None},
            "B": {"answer": "x = 8",    "misconception": "adds 5 to both sides instead of subtracting"},
            "C": {"answer": "x = 6.6",  "misconception": "divides 20 by 3 without subtracting 5 first"},
            "D": {"answer": "x = 15",   "misconception": "subtracts 5 from 20 but forgets to divide by 3"}
        }
    },
    {
        "id": 2,
        "topic": "Algebra",
        "subtopic": "Expanding brackets",
        "question": "Expand: 3(x + 4)",
        "correct": "B",
        "options": {
            "A": {"answer": "3x + 4",   "misconception": "only multiplies the first term, ignores second"},
            "B": {"answer": "3x + 12",  "misconception": None},
            "C": {"answer": "x + 12",   "misconception": "only multiplies the second term, ignores first"},
            "D": {"answer": "3x + 7",   "misconception": "adds 3 to 4 instead of multiplying"}
        }
    },
    {
        "id": 3,
        "topic": "Algebra",
        "subtopic": "Substitution",
        "question": "If x = 3, what is 2x² + 1?",
        "correct": "C",
        "options": {
            "A": {"answer": "13",  "misconception": "calculates (2x)² instead of 2(x²)"},
            "B": {"answer": "37",  "misconception": "computes 2x then squares the result"},
            "C": {"answer": "19",  "misconception": None},
            "D": {"answer": "7",   "misconception": "ignores the square, treats as 2x + 1"}
        }
    },
    {
        "id": 4,
        "topic": "Algebra",
        "subtopic": "Factorising",
        "question": "Factorise: x² + 5x + 6",
        "correct": "A",
        "options": {
            "A": {"answer": "(x + 2)(x + 3)",  "misconception": None},
            "B": {"answer": "(x + 1)(x + 6)",  "misconception": "finds factors of 6 that add to 7, not 5"},
            "C": {"answer": "(x + 5)(x + 1)",  "misconception": "uses the coefficient 5 directly as a factor"},
            "D": {"answer": "(x − 2)(x − 3)",  "misconception": "uses wrong signs, ignores positive constant"}
        }
    },
    {
        "id": 5,
        "topic": "Algebra",
        "subtopic": "Inequalities",
        "question": "Solve: 2x − 3 > 7",
        "correct": "B",
        "options": {
            "A": {"answer": "x > 2",   "misconception": "divides 7 by 2 without adding 3 first"},
            "B": {"answer": "x > 5",   "misconception": None},
            "C": {"answer": "x > 5, flips sign", "misconception": "incorrectly flips inequality sign without dividing by negative"},
            "D": {"answer": "x < 5",   "misconception": "flips inequality sign for no reason"}
        }
    },

    # ── FRACTIONS & DECIMALS ─────────────────
    {
        "id": 6,
        "topic": "Fractions",
        "subtopic": "Adding fractions",
        "question": "What is 2/3 + 1/4?",
        "correct": "B",
        "options": {
            "A": {"answer": "3/7",   "misconception": "adds numerators and denominators separately"},
            "B": {"answer": "11/12", "misconception": None},
            "C": {"answer": "3/12",  "misconception": "finds common denominator but forgets to scale numerators"},
            "D": {"answer": "2/7",   "misconception": "subtracts instead of adds"}
        }
    },
    {
        "id": 7,
        "topic": "Fractions",
        "subtopic": "Multiplying fractions",
        "question": "What is 3/4 × 2/5?",
        "correct": "A",
        "options": {
            "A": {"answer": "6/20 = 3/10", "misconception": None},
            "B": {"answer": "5/9",         "misconception": "adds numerators and denominators instead of multiplying"},
            "C": {"answer": "6/5",         "misconception": "multiplies numerators but keeps one denominator"},
            "D": {"answer": "15/8",        "misconception": "flips second fraction before multiplying (divides instead)"}
        }
    },
    {
        "id": 8,
        "topic": "Fractions",
        "subtopic": "Fraction of an amount",
        "question": "What is 3/5 of 40?",
        "correct": "C",
        "options": {
            "A": {"answer": "8",   "misconception": "divides by 5 but forgets to multiply by 3"},
            "B": {"answer": "15",  "misconception": "multiplies 40 × 3 then divides by 8 instead of 5"},
            "C": {"answer": "24",  "misconception": None},
            "D": {"answer": "120", "misconception": "multiplies 40 × 3 without dividing"}
        }
    },

    # ── PERCENTAGES ──────────────────────────
    {
        "id": 9,
        "topic": "Percentages",
        "subtopic": "Percentage of an amount",
        "question": "What is 35% of 120?",
        "correct": "A",
        "options": {
            "A": {"answer": "42",   "misconception": None},
            "B": {"answer": "35",   "misconception": "gives the percentage itself, ignores the amount"},
            "C": {"answer": "4.2",  "misconception": "divides by 100 but forgets to multiply by 120"},
            "D": {"answer": "85",   "misconception": "adds 35 to 120 instead of finding the percentage"}
        }
    },
    {
        "id": 10,
        "topic": "Percentages",
        "subtopic": "Percentage increase",
        "question": "A price increases from £80 to £100. What is the percentage increase?",
        "correct": "B",
        "options": {
            "A": {"answer": "20%",  "misconception": "uses the difference (20) as the percentage without dividing by original"},
            "B": {"answer": "25%",  "misconception": None},
            "C": {"answer": "80%",  "misconception": "divides original by new price"},
            "D": {"answer": "125%", "misconception": "calculates new as percentage of original instead of increase"}
        }
    },
    {
        "id": 11,
        "topic": "Percentages",
        "subtopic": "Reverse percentage",
        "question": "After a 20% discount, a jacket costs £64. What was the original price?",
        "correct": "C",
        "options": {
            "A": {"answer": "£76.80", "misconception": "adds 20% to the discounted price instead of reversing"},
            "B": {"answer": "£51.20", "misconception": "subtracts 20% from the discounted price"},
            "C": {"answer": "£80",    "misconception": None},
            "D": {"answer": "£84",    "misconception": "divides by 0.8 but miscalculates"}
        }
    },

    # ── GEOMETRY ─────────────────────────────
    {
        "id": 12,
        "topic": "Geometry",
        "subtopic": "Area of a triangle",
        "question": "A triangle has base 10cm and height 6cm. What is its area?",
        "correct": "A",
        "options": {
            "A": {"answer": "30 cm²", "misconception": None},
            "B": {"answer": "60 cm²", "misconception": "uses base × height without halving"},
            "C": {"answer": "16 cm²", "misconception": "adds base and height instead of multiplying"},
            "D": {"answer": "15 cm²", "misconception": "halves the base instead of the product"}
        }
    },
    {
        "id": 13,
        "topic": "Geometry",
        "subtopic": "Circle area",
        "question": "What is the area of a circle with radius 5cm? (use π = 3.14)",
        "correct": "B",
        "options": {
            "A": {"answer": "15.7 cm²",  "misconception": "uses 2πr (circumference formula) instead of area"},
            "B": {"answer": "78.5 cm²",  "misconception": None},
            "C": {"answer": "314 cm²",   "misconception": "uses diameter instead of radius"},
            "D": {"answer": "31.4 cm²",  "misconception": "forgets to square the radius"}
        }
    },
    {
        "id": 14,
        "topic": "Geometry",
        "subtopic": "Angles in parallel lines",
        "question": "Two parallel lines are cut by a transversal. One angle is 65°. What is the co-interior angle?",
        "correct": "D",
        "options": {
            "A": {"answer": "65°",  "misconception": "confuses co-interior with alternate angles"},
            "B": {"answer": "25°",  "misconception": "subtracts from 90° instead of 180°"},
            "C": {"answer": "35°",  "misconception": "subtracts angle from 100°"},
            "D": {"answer": "115°", "misconception": None}
        }
    },
    {
        "id": 15,
        "topic": "Geometry",
        "subtopic": "Pythagoras theorem",
        "question": "A right triangle has legs 6cm and 8cm. What is the hypotenuse?",
        "correct": "A",
        "options": {
            "A": {"answer": "10 cm",  "misconception": None},
            "B": {"answer": "14 cm",  "misconception": "adds the two sides instead of using Pythagoras"},
            "C": {"answer": "7 cm",   "misconception": "averages the two sides"},
            "D": {"answer": "100 cm", "misconception": "finds a² + b² but forgets to square root"}
        }
    },

    # ── RATIO & PROPORTION ───────────────────
    {
        "id": 16,
        "topic": "Ratio",
        "subtopic": "Sharing in a ratio",
        "question": "Share £120 in the ratio 3:5. What is the larger share?",
        "correct": "B",
        "options": {
            "A": {"answer": "£45",  "misconception": "divides by 3 and 5 separately without finding one part first"},
            "B": {"answer": "£75",  "misconception": None},
            "C": {"answer": "£72",  "misconception": "divides total by ratio numbers directly"},
            "D": {"answer": "£60",  "misconception": "divides total equally then adjusts wrong"}
        }
    },
    {
        "id": 17,
        "topic": "Ratio",
        "subtopic": "Direct proportion",
        "question": "5 pens cost £3.50. How much do 8 pens cost?",
        "correct": "C",
        "options": {
            "A": {"answer": "£4.50",  "misconception": "adds £1 per extra pen instead of finding unit cost"},
            "B": {"answer": "£5.60",  "misconception": "multiplies 3.50 by 8 without dividing by 5 first"},
            "C": {"answer": "£5.60 → wait, correct is £5.60", "misconception": None},
            "D": {"answer": "£6.00",  "misconception": "rounds unit cost before multiplying, loses precision"}
        }
    },

    # ── NUMBER & ARITHMETIC ──────────────────
    {
        "id": 18,
        "topic": "Number",
        "subtopic": "Order of operations",
        "question": "Calculate: 3 + 4 × 2 − 1",
        "correct": "A",
        "options": {
            "A": {"answer": "10",  "misconception": None},
            "B": {"answer": "13",  "misconception": "works left to right, ignores BODMAS/order of operations"},
            "C": {"answer": "7",   "misconception": "subtracts before multiplying"},
            "D": {"answer": "14",  "misconception": "adds 3+4 first then multiplies"}
        }
    },
    {
        "id": 19,
        "topic": "Number",
        "subtopic": "Negative numbers",
        "question": "What is −3 × −4?",
        "correct": "B",
        "options": {
            "A": {"answer": "−12",  "misconception": "ignores sign rules, treats as positive × positive = negative"},
            "B": {"answer": "12",   "misconception": None},
            "C": {"answer": "−7",   "misconception": "adds instead of multiplies"},
            "D": {"answer": "7",    "misconception": "adds absolute values, applies wrong sign"}
        }
    },
    {
        "id": 20,
        "topic": "Number",
        "subtopic": "Standard form",
        "question": "Write 0.0047 in standard form.",
        "correct": "C",
        "options": {
            "A": {"answer": "4.7 × 10²",   "misconception": "uses positive power instead of negative"},
            "B": {"answer": "47 × 10⁻⁴",   "misconception": "does not write as a number between 1 and 10"},
            "C": {"answer": "4.7 × 10⁻³",  "misconception": None},
            "D": {"answer": "0.47 × 10⁻²", "misconception": "moves decimal point but not to correct position"}
        }
    }
]


# ─────────────────────────────────────────────
# STUDENT ANSWERS
# In real app this comes from Learnosity
# For demo: simulate a Year 8 student
# ─────────────────────────────────────────────

student = {
    "name": "Ahmed",
    "age": 13,
    "year": 8,
    "answers": {
        1:  "B",  # wrong — algebra
        2:  "B",  # correct
        3:  "A",  # wrong — algebra
        4:  "A",  # correct
        5:  "D",  # wrong — inequalities
        6:  "A",  # wrong — fractions
        7:  "A",  # correct
        8:  "A",  # wrong — fractions
        9:  "A",  # correct
        10: "A",  # wrong — percentages
        11: "A",  # wrong — percentages
        12: "B",  # wrong — geometry
        13: "B",  # correct
        14: "A",  # wrong — geometry
        15: "A",  # correct
        16: "B",  # correct
        17: "C",  # correct
        18: "B",  # wrong — BODMAS
        19: "B",  # correct
        20: "A",  # wrong — standard form
    }
}


# ─────────────────────────────────────────────
# ANALYSIS ENGINE
# Compares answers to question bank
# Extracts misconceptions per topic
# ─────────────────────────────────────────────

def analyze_student(student, question_bank):
    results = []
    topic_summary = {}

    for q in question_bank:
        qid = q["id"]
        student_answer = student["answers"].get(qid)
        correct = q["correct"]
        is_correct = student_answer == correct

        misconception = None
        if not is_correct and student_answer in q["options"]:
            misconception = q["options"][student_answer]["misconception"]

        results.append({
            "id": qid,
            "topic": q["topic"],
            "subtopic": q["subtopic"],
            "correct": is_correct,
            "misconception": misconception
        })

        # group by topic
        topic = q["topic"]
        if topic not in topic_summary:
            topic_summary[topic] = {"correct": 0, "total": 0, "misconceptions": []}
        topic_summary[topic]["total"] += 1
        if is_correct:
            topic_summary[topic]["correct"] += 1
        if misconception:
            topic_summary[topic]["misconceptions"].append(
                f"{q['subtopic']}: {misconception}"
            )

    return results, topic_summary


# ─────────────────────────────────────────────
# REPORT GENERATOR
# Sends analysis to Claude API
# Gets back a parent-friendly report
# ─────────────────────────────────────────────

def generate_report(student, topic_summary):
    client = anthropic.Anthropic()

    # build a clear summary to send to Claude
    topic_lines = []
    for topic, data in topic_summary.items():
        pct = round(data["correct"] / data["total"] * 100)
        misconceptions = data["misconceptions"]
        line = f"- {topic}: {data['correct']}/{data['total']} correct ({pct}%)"
        if misconceptions:
            line += "\n  Detected gaps:\n"
            for m in misconceptions:
                line += f"    * {m}\n"
        topic_lines.append(line)

    topic_text = "\n".join(topic_lines)

    total_correct = sum(r["correct"] for r in results)
    overall_pct = round(total_correct / len(results) * 100)

    prompt = f"""
You are an expert educational consultant at a tutoring center.

A Year 8 student named {student['name']} (age {student['age']}) just completed a math assessment.

Here are the results with specific detected misconceptions:

Overall score: {total_correct}/{len(results)} ({overall_pct}%)

{topic_text}

Please write a professional report for the center director to share with the parents.
The report should:
1. Start with a warm, encouraging overall summary
2. Highlight what the student does well
3. Clearly explain each detected gap in simple, parent-friendly language (no jargon)
4. Give 3-4 specific, actionable recommendations for what to focus on in tutoring sessions
5. End with an encouraging closing message

Keep the tone warm, professional, and constructive.
Write it as if you are speaking directly to the parents.
"""

    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=1000,
        messages=[{"role": "user", "content": prompt}]
    )

    return message.content[0].text


# ─────────────────────────────────────────────
# RUN EVERYTHING
# ─────────────────────────────────────────────

print(f"\nAnalyzing {student['name']}'s assessment...\n")

results, topic_summary = analyze_student(student, question_bank)

print("=" * 50)
print("TOPIC BREAKDOWN")
print("=" * 50)
for topic, data in topic_summary.items():
    pct = round(data["correct"] / data["total"] * 100)
    bar = "█" * (pct // 10) + "░" * (10 - pct // 10)
    print(f"{topic:<15} {bar} {pct}%")
    for m in data["misconceptions"]:
        print(f"  ⚠ {m}")

print("\n" + "=" * 50)
print("GENERATING PARENT REPORT...")
print("=" * 50 + "\n")

report = generate_report(student, topic_summary)
print(report)